name: "🐞 Bug Report"
description: "Report an issue or unexpected behavior in the Library Management System."
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        Thank you for taking the time to report an issue. Please fill out the details below to help us investigate the problem effectively.

  - type: input
    id: bug-title
    attributes:
      label: "Short Description"
      description: "Summarize the issue in a single sentence."
      placeholder: "Example: The application crashes when borrowing a book."
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: "Detailed Description"
      description: "Provide a detailed explanation of the issue, including what you expected to happen versus what actually happened."
      placeholder: "Describe the issue here..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to replicate this issue."
      placeholder: |
        1. Open the application.
        2. Try to borrow a book that is already borrowed.
        3. Observe the error.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe what should happen instead."
      placeholder: "The system should display an error message instead of crashing."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually happens when the issue occurs."
      placeholder: "The application crashes with an unhandled exception."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs & Screenshots (if applicable)"
      description: "Include error messages, logs, or screenshots that could help identify the problem."
      placeholder: "Paste error logs here..."

  - type: input
    id: environment
    attributes:
      label: "Environment (OS, .NET version, etc.)"
      description: "Specify the operating system and .NET version you're using."
      placeholder: "Windows 11, .NET 7.0"

  - type: dropdown
    id: priority
    attributes:
      label: "Priority Level"
      description: "How critical is this issue?"
      options:
        - "Low"
        - "Medium"
        - "High"
        - "Critical"
    validations:
      required: true
