name: "🐞 Bug Report"
description: "Report a bug to help improve the project."
title: "[Bug] <short description>"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "## 🐛 Bug Report\nPlease describe the issue in detail."

  - type: textarea
    id: description
    attributes:
      label: "Describe the Bug"
      description: "A clear and concise description of what the bug is."
      placeholder: "Explain the issue here..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the bug."
      placeholder: |
        1. Run the application
        2. Select option X
        3. Enter Y
        4. Observe the issue
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: "What should have happened?"
      placeholder: "Describe the expected behavior..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual Behavior"
      description: "What actually happened?"
      placeholder: "Describe the actual behavior..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Relevant Logs/Error Messages"
      description: "Paste any error logs or screenshots."
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: "Select the OS where the issue occurs."
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Application Version"
      description: "Which version of the application are you using?"
      placeholder: "v1.0.0"

  - type: checkboxes
    id: additional
    attributes:
      label: "Additional Information"
      options:
        - label: "I have searched for existing issues before opening this."
          required: true
