name: "📝 Documentation Improvement"
description: "Suggest improvements or updates for the project documentation."
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Improvement
        Thank you for helping us improve our documentation! Please provide details about the suggested improvements.

  - type: input
    id: docs-section
    attributes:
      label: "Affected Documentation Section"
      description: "Which section of the documentation needs improvement?"
      placeholder: "Example: Installation Guide, README.md, CONTRIBUTING.md"
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: "Describe the Issue"
      description: "What needs to be improved or updated?"
      placeholder: "The installation steps are outdated and need to be revised."
    validations:
      required: true

  - type: textarea
    id: proposed-changes
    attributes:
      label: "Proposed Changes"
      description: "Describe how the documentation should be updated."
      placeholder: "Update the prerequisites to include .NET 7 and add missing dependencies."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority Level"
      description: "How urgent is this improvement?"
      options:
        - "Low"
        - "Medium"
        - "High"
        - "Critical"
    validations:
      required: true
