name: "Feature Request"
description: "Suggest a new feature for the Temperature Calculator"
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - aiman-11

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request
        Thank you for suggesting an improvement! Please provide details below.

  - type: input
    id: feature_title
    attributes:
      label: "Feature Title"
      description: "A short and clear title for the feature request."
      placeholder: "Example: Add Temperature History Logging"
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "Explain what this feature does and why it's useful."
      placeholder: "Describe the feature in detail..."
    validations:
      required: true

  - type: textarea
    id: implementation_details
    attributes:
      label: "Proposed Implementation"
      description: "How do you suggest this feature should be implemented?"
      placeholder: "Provide implementation details if possible..."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: "How urgent is this feature?"
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: checkboxes
    id: additional_context
    attributes:
      label: "Additional Context"
      description: "Check any relevant points below:"
      options:
        - label: "This feature improves user experience"
        - label: "This feature adds new functionality"
        - label: "This feature fixes an existing limitation"

  - type: textarea
    id: additional_notes
    attributes:
      label: "Additional Notes (Optional)"
      description: "Any extra details or references?"
