name: "💡 Feature Request"
description: "Propose a new feature for the application."
title: "[Feature] <short description>"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: "## 💡 Feature Request\nPropose a new feature for the project."

  - type: textarea
    id: feature
    attributes:
      label: "Feature Description"
      description: "What new feature would you like to see?"
      placeholder: "Describe the feature..."
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: "Use Case"
      description: "How will this feature be useful?"
      placeholder: "Describe the purpose and benefit..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Alternative Solutions"
      description: "Have you considered any alternatives?"
      placeholder: "List any alternative solutions..."
  
  - type: checkboxes
    id: additional
    attributes:
      label: "Additional Information"
      options:
        - label: "I have searched for existing issues before opening this."
          required: true
